### ISSUE TITLE
希望能增加个自定义发包的接口

### ISSUE THREAD

**Issue by youyon** [fuqiuluo/Shamrock#15]
RT，通过TXHook抓到的数据包无法修改后重新发包，希望这个项目能新增一个。

**Comment by fuqiuluo** [comment]
已实现，[点我前往}(https://github.com/fuqiuluo/Shamrock/wiki/onebot_http#%E5%8D%8F%E8%AE%AE%E6%95%B0%E6%8D%AE)

**Comment by fuqiuluo** [comment]
已支持自定义发包收返回包
