### ISSUE TITLE
可不可以添加access_token

### ISSUE THREAD

**Issue by ayakasuki** [fuqiuluo/Shamrock#17]
可不可以添加access_token这一项呢？因为公网可能要使用到

**Comment by callng** [comment]
hahahhhhhhhhhhhhhhhhh matryoshka

**Comment by ayakasuki** [comment]
> 推荐使用nginx反向代理，使用BasicAuth
反向代理以后 BasicAuth有用户名和密码 请教一下access_token怎么填呢？uptime_kuma以及twikoo推送都要求填写access_token来着

**Comment by ayakasuki** [comment]
我觉得加了jwt oauth2都太复杂 basicauth我试过无法access_token使用，用的是用户名和密码。。我感觉不如为了兼容性，迎合onebot现有的鉴权模式添加access_token就好了

**Comment by fuqiuluo** [comment]
# HTTP 和正向 WebSocket
如果配置文件中填写了 access token，则每次客户端向 OneBot 发送请求时需要在请求头中加入 Authorization 头，如：

```
GET /get_friend_list HTTP/1.1
Authorization: Bearer kSLuTF2GC2Q4q4ugm3
```
Bearer 后面需给出和 OneBot 配置中相同的 access token。

在某些特殊情况下，可能无法修改请求头，则可以通过 query 参数传入 access token，例如：

GET /get_friend_list?access_token=kSLuTF2GC2Q4q4ugm3 HTTP/1.1

# 反向 WebSocket

如果配置文件中填写了 access token，则每次 OneBot 的反向 WebSocket 客户端在向用户配置的 URL 建立连接的时候，会在请求头中加入 Authorization 头，如：

```
GET /ws/api HTTP/1.1
Authorization: Bearer kSLuTF2GC2Q4q4ugm3
```

> 他的这个标准相当零散，一下用`GET`传递token，一下用`HEADER`传递，很明显的屎山代码。

**Comment by fuqiuluo** [comment]
新版本支持了，后面会提交

**Comment by ayakasuki** [comment]
> 新版本支持了，后面会提交

好滴 阿里嘎多！
