### ISSUE TITLE
希望日志能够存储到文件或者提供接口给外部获取

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [fuqiuluo/Shamrock#2]
gocq屏显日志非常的详细，使用 `nohup go-cqhttp &` 命令启动就可以把自动生成的 nohup 文件当做消息记录文件，希望Shamrock也提供类似的功能，如果可以的话，采用 rotatelog 的模式更好，这样外部就可以随意修改或移动文件，而不影响主程序运行并正常记录文件了。

Shamrock提供监听一个端口，对连接上来的客户端自动发送日志消息，也是个可选方案

**Comment by fuqiuluo** [comment]
可否提供一个日志格式？

**Comment by fuqiuluo** [comment]
访问HTTP外部接口`http://xxx.xxx.xxx.xxx/log`即可获得log日志
